// Generated by CoffeeScript 1.8.0
(function() {
  var Anchor, Element, Frame, FrameContent, _base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Element = (function() {
    var addClass, addEventListener, hasClass, r_leading_and_trailing_whitespace, r_whitespace, removeClass, removeEventListener;

    function Element(element, callback) {
      this.element = element && element.nodeType === 1 ? element : document.createElement(element);
      if (callback) {
        callback(this.element);
      }
    }

    Element.prototype.on = function(event, func) {
      addEventListener(this.element, event, func);
    };

    Element.prototype.once = function(event, func) {
      var once;
      once = (function(_this) {
        return function() {
          removeEventListener(_this.element, event, once);
          func();
        };
      })(this);
      addEventListener(this.element, event, once);
    };

    Element.prototype.addClass = function(className) {
      if (!hasClass(this.element, className)) {
        addClass(this.element, className);
      }
    };

    Element.prototype.removeClass = function(className) {
      if (hasClass(this.element, className)) {
        removeClass(this.element, className);
      }
    };

    Element.prototype.hasClass = function(className) {
      return hasClass(this.element, className);
    };

    addEventListener = function(element, event, func) {
      if (element.addEventListener) {
        element.addEventListener("" + event, func);
      } else {
        element.attachEvent("on" + event, func);
      }
    };

    removeEventListener = function(element, event, func) {
      if (element.removeEventListener) {
        element.removeEventListener("" + event, func);
      } else {
        element.detachEvent("on" + event, func);
      }
    };

    r_whitespace = /[ \t\n\f\r]+/g;

    r_leading_and_trailing_whitespace = /^[ \t\n\f\r]+|[ \t\n\f\r]+$/g;

    addClass = function(element, className) {
      element.className += " " + className;
    };

    removeClass = function(element, className) {
      element.className = (" " + element.className + " ").replace(r_whitespace, " ").replace(" " + className + " ", "").replace(r_leading_and_trailing_whitespace, "");
    };

    hasClass = function(element, className) {
      return (" " + element.className + " ").replace(r_whitespace, " ").indexOf(" " + className + " ") >= 0;
    };

    return Element;

  })();

  Anchor = (function() {
    var filter_js;

    function Anchor() {}

    Anchor.parse = function(element) {
      return {
        href: filter_js(element.href),
        text: element.getAttribute("data-text") || element.textContent || element.innerText,
        data: {
          count: {
            api: (function() {
              var api;
              if (api = element.getAttribute("data-count-api")) {
                if ("/" !== api.charAt(0)) {
                  api = "/" + api;
                }
                return api;
              }
            })(),
            href: (function() {
              var href;
              if ((href = element.getAttribute("data-count-href")) && (href = filter_js(href))) {
                return href;
              } else {
                return filter_js(element.href);
              }
            })()
          },
          style: (function() {
            var i, style, _i, _len, _ref;
            if (style = element.getAttribute("data-style")) {
              _ref = Config.styles;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                i = _ref[_i];
                if (i === style) {
                  return style;
                }
              }
            }
            return Config.styles[0];
          })(),
          icon: (function() {
            var icon;
            if (icon = element.getAttribute("data-icon")) {
              return icon;
            }
          })()
        }
      };
    };

    filter_js = function(href) {
      if (!/^\s*javascript:/i.test(href)) {
        return href;
      }
    };

    return Anchor;

  })();

  Frame = (function(_super) {
    __extends(Frame, _super);

    function Frame() {
      var callback, hash;
      hash = arguments[0], callback = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      this.hash = hash;
      this.callback = callback;
      Frame.__super__.constructor.call(this, "iframe", function(iframe) {
        var key, value, _ref, _ref1;
        _ref = {
          allowtransparency: true,
          scrolling: "no",
          frameBorder: 0
        };
        for (key in _ref) {
          value = _ref[key];
          iframe.setAttribute(key, value);
        }
        _ref1 = {
          border: "none",
          height: "0",
          width: "1px"
        };
        for (key in _ref1) {
          value = _ref1[key];
          iframe.style[key] = value;
        }
        if (callback[0]) {
          callback[0](iframe);
        }
      });
      this.once("load", (function(_this) {
        return function() {
          var event, script, _i, _len, _ref;
          if (_this.element.contentWindow.callback) {
            script = _this.element.contentWindow.callback.script;
            if (script.readyState) {
              _this.on.call({
                element: script
              }, "readystatechange", function() {
                if (/loaded|complete/.test(script.readyState)) {
                  _this.reload();
                }
              });
            } else {
              _ref = ["load", "error"];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                event = _ref[_i];
                _this.on.call({
                  element: script
                }, event, function() {
                  _this.reload();
                });
              }
            }
          } else {
            _this.reload();
          }
        };
      })(this));
      this.element.contentWindow.document.open();
      this.element.contentWindow.document.write("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<title></title>\n<base target=\"_blank\"><!--[if lte IE 6]></base><![endif]-->\n<link rel=\"stylesheet\" href=\"" + Config.url + "assets/css/buttons.css\">\n<style>html{visibility:hidden;}</style>\n<script>document.location.hash = \"" + this.hash + "\";</script>\n</head>\n<body>\n<script src=\"" + Config.script.src + "\"></script>\n</body>\n</html>");
      this.element.contentWindow.document.close();
    }

    Frame.prototype.reload = function() {
      var body, contentDocument, html, style;
      contentDocument = this.element.contentWindow.document;
      html = contentDocument.documentElement;
      body = contentDocument.body;
      html.style.overflow = body.style.overflow = window.opera ? "scroll" : "visible";
      style = {
        height: "" + body.scrollHeight + "px",
        width: "" + body.scrollWidth + "px"
      };
      html.style.overflow = body.style.overflow = "";
      this.once("load", (function(_this) {
        return function() {
          var key, value;
          for (key in style) {
            value = style[key];
            _this.element.style[key] = value;
          }
          if (_this.callback[1]) {
            _this.callback[1](_this.element);
          }
        };
      })(this));
      this.element.src = "" + Config.url + "buttons.html" + this.hash;
    };

    return Frame;

  })(Element);

  FrameContent = (function() {
    var Button, Count;

    function FrameContent(options) {
      if (options && options.data) {
        document.body.className = options.data.style;
        document.getElementsByTagName("base")[0].href = options.href;
        new Button(options, function(buttonElement) {
          document.body.appendChild(buttonElement);
        });
        new Count(options, function(countElement) {
          document.body.appendChild(countElement);
        });
      }
    }

    Button = (function(_super) {
      __extends(Button, _super);

      function Button(options, callback) {
        Button.__super__.constructor.call(this, "a", function(a) {
          a.className = "button";
          if (options.href) {
            a.href = options.href;
          }
          new Element("i", function(icon) {
            icon = document.createElement("i");
            icon.className = (function() {
              var classNames;
              classNames = [options.data.icon || Config.icon];
              if (Config.iconClass) {
                classNames.push(Config.iconClass);
              }
              return classNames.join(" ");
            })();
            a.appendChild(icon);
          });
          new Element("span", function(text) {
            text.appendChild(document.createTextNode(" "));
            a.appendChild(text);
          });
          new Element("span", function(text) {
            if (options.text) {
              text.appendChild(document.createTextNode(options.text));
            }
            a.appendChild(text);
          });
          if (callback) {
            callback(a);
          }
        });
      }

      return Button;

    })(Element);

    Count = (function(_super) {
      __extends(Count, _super);

      function Count(options, callback) {
        if (options.data.count.api) {
          Count.__super__.constructor.call(this, "a", function(a) {
            a.className = "count";
            if (options.data.count.href) {
              a.href = options.data.count.href;
            }
            new Element("b", function(b) {
              a.appendChild(b);
            });
            new Element("i", function(i) {
              a.appendChild(i);
            });
            new Element("span", function(text) {
              var endpoint;
              a.appendChild(text);
              endpoint = (function() {
                var query, url;
                url = options.data.count.api.split("#")[0];
                query = QueryString.parse(url.split("?").slice(1).join("?"));
                query.callback = "callback";
                return "" + (url.split("?")[0]) + "?" + (QueryString.stringify(query));
              })();
              new Element("script", function(script) {
                var head;
                script.async = true;
                script.src = "" + Config.api + endpoint;
                window.callback = function(json) {
                  var data;
                  window.callback = null;
                  if (json.meta.status === 200) {
                    data = FlatObject.flatten(json.data)[options.data.count.api.split("#").slice(1).join("#")];
                    if (Object.prototype.toString.call(data) === "[object Number]") {
                      data = data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                    }
                    text.appendChild(document.createTextNode(" " + data + " "));
                    if (callback) {
                      callback(a);
                    }
                  }
                };
                window.callback.script = script;
                Element.prototype.on.call({
                  element: script
                }, "error", function() {
                  window.callback = null;
                });
                if (script.readyState) {
                  Element.prototype.on.call({
                    element: script
                  }, "readystatechange", function() {
                    if (script.readyState === "loaded" && script.children && script.readyState === "loading") {
                      window.callback = null;
                    }
                  });
                }
                head = document.getElementsByTagName("head")[0];
                head.insertBefore(script, head.firstChild);
              });
            });
          });
        }
      }

      return Count;

    })(Element);

    return FrameContent;

  })();

  if (window._phantom) {
    (_base = HTMLElement.prototype).click || (_base.click = function() {
      var ev;
      ev = document.createEvent('MouseEvent');
      ev.initMouseEvent('click', true, true, window, null, 0, 0, 0, 0, false, false, false, false, 0, null);
      this.dispatchEvent(ev);
    });
  }

  describe('Element', function() {
    describe('#constructor()', function() {
      it('should use element when element is given', function() {
        var element;
        element = document.createElement("a");
        return expect(new Element(element)).to.have.property("element", element);
      });
      it('should create new element when tag name is given', function() {
        return expect(new Element("i")).to.have.deep.property("element.nodeType", 1);
      });
      return it('should callback with the element', function(done) {
        var b;
        b = document.createElement("b");
        return new Element(b, function(element) {
          expect(element).to.equal(b);
          return done();
        });
      });
    });
    describe('#on()', function() {
      return it('should call the function on event', function() {
        var a, spy;
        spy = sinon.spy();
        a = new Element("a");
        a.on("click", spy);
        a.element.click();
        expect(spy).to.have.been.calledOnce;
        a.element.click();
        return expect(spy).to.have.been.calledTwice;
      });
    });
    describe('#once()', function() {
      return it('should call the function on event only once', function() {
        var a, spy;
        spy = sinon.spy();
        a = new Element("a");
        a.once("click", spy);
        a.element.click();
        expect(spy).to.have.been.calledOnce;
        a.element.click();
        a.element.click();
        return expect(spy).to.have.been.calledOnce;
      });
    });
    describe('#addClass()', function() {
      return it('should add class to element', function() {
        var a, element;
        element = document.createElement("a");
        element.className = "hello";
        a = new Element(element);
        a.addClass("world");
        expect(a.element.className).to.equal("hello world");
        a.addClass("world");
        return expect(a.element.className).to.equal("hello world");
      });
    });
    describe('#removeClass()', function() {
      return it('should remove class from element', function() {
        var a, element;
        element = document.createElement("a");
        element.className = "hello world";
        a = new Element(element);
        a.removeClass("hello");
        expect(a.element.className).to.equal("world");
        a.removeClass("hello");
        return expect(a.element.className).to.equal("world");
      });
    });
    return describe('#hasClass()', function() {
      return it('should return whether element has class', function() {
        var a, element;
        element = document.createElement("a");
        element.className = "world";
        a = new Element(element);
        expect(a.hasClass("hello")).to.be["false"];
        return expect(a.hasClass("world")).to.be["true"];
      });
    });
  });

}).call(this);
