// Generated by CoffeeScript 1.8.0
(function() {
  var ButtonAnchor, ButtonFrame, ButtonFrameContent, Config, Element, FlatObject, Frame, Hash, QueryString, anchor, anchors, _fn, _i, _len,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Config = {
    api: "https://api.github.com",
    anchorClass: "github-button",
    iconClass: "octicon",
    icon: "octicon-mark-github",
    scriptId: "github-bjs",
    styles: ["default", "mega"]
  };

  if (Config.script = document.getElementById(Config.scriptId)) {
    Config.url = Config.script.src.replace(/[?#].*$/, "").replace(/buttons.js$/, "");
  }

  FlatObject = (function() {
    var __toString;

    function FlatObject() {}

    FlatObject.flatten = function(obj) {
      var flatten, result;
      flatten = function(object, super_key) {
        var index, item, key, value, _i, _len;
        switch (__toString.call(object)) {
          case "[object Object]":
            for (key in object) {
              value = object[key];
              flatten(value, super_key ? "" + super_key + "." + key : key);
            }
            break;
          case "[object Array]":
            for (index = _i = 0, _len = object.length; _i < _len; index = ++_i) {
              item = object[index];
              flatten(item, super_key ? "" + super_key + "[" + index + "]" : "[" + index + "]");
            }
            break;
          default:
            result[super_key] = object;
        }
      };
      result = {};
      flatten(obj);
      return result;
    };

    FlatObject.expand = function(obj) {
      var flat_key, key, keys, match, namespace, sub_key, target, value, _i, _j, _len, _len1, _ref, _ref1;
      namespace = [];
      for (flat_key in obj) {
        value = obj[flat_key];
        keys = [];
        _ref = flat_key.split(".");
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          match = key.match(/^(.*?)((?:\[[0-9]+\])*)$/);
          if (match[1]) {
            keys.push(match[1]);
          }
          if (match[2]) {
            _ref1 = match[2].replace(/^\[|\]$/g, "").split("][");
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              sub_key = _ref1[_j];
              keys.push(Number(sub_key));
            }
          }
        }
        target = namespace;
        key = 0;
        while (keys.length) {
          if (target[key] == null) {
            switch (__toString.call(keys[0])) {
              case "[object String]":
                target[key] = {};
                break;
              case "[object Number]":
                target[key] = [];
            }
          }
          target = target[key];
          key = keys.shift();
        }
        target[key] = value;
      }
      return namespace[0];
    };

    __toString = Object.prototype.toString;

    return FlatObject;

  })();

  QueryString = (function() {
    function QueryString() {}

    QueryString.stringify = function(obj) {
      var key, results, value;
      results = [];
      for (key in obj) {
        value = obj[key];
        if (value == null) {
          value = "";
        }
        results.push("" + key + "=" + value);
      }
      return results.join("&");
    };

    QueryString.parse = function(str) {
      var key, obj, pair, value, _i, _len, _ref, _ref1;
      obj = {};
      _ref = str.split("&");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pair = _ref[_i];
        if (!(pair !== "")) {
          continue;
        }
        _ref1 = pair.split("="), key = _ref1[0], value = 2 <= _ref1.length ? __slice.call(_ref1, 1) : [];
        if (key !== "") {
          obj[key] = value.join("=");
        }
      }
      return obj;
    };

    return QueryString;

  })();

  Hash = (function() {
    function Hash() {}

    Hash.encode = function(data) {
      return "#" + encodeURIComponent(QueryString.stringify(FlatObject.flatten(data)));
    };

    Hash.decode = function(data) {
      if (data == null) {
        data = document.location.hash;
      }
      return (FlatObject.expand(QueryString.parse(decodeURIComponent(data.replace(/^#/, ""))))) || {};
    };

    return Hash;

  })();

  Element = (function() {
    var addClass, addEventListener, hasClass, r_leading_and_trailing_whitespace, r_whitespace, removeClass, removeEventListener;

    function Element(element, callback) {
      this.element = element && element.nodeType === 1 ? element : document.createElement(element);
      if (callback) {
        callback.apply(this, [this.element]);
      }
    }

    Element.prototype.on = function() {
      var callback, event, events, func, _i, _j, _len;
      events = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), func = arguments[_i++];
      callback = (function(_this) {
        return function() {
          func.apply(_this, [_this.element]);
        };
      })(this);
      for (_j = 0, _len = events.length; _j < _len; _j++) {
        event = events[_j];
        addEventListener(this.element, event, callback);
      }
    };

    Element.prototype.once = function() {
      var callback, event, events, func, _i, _j, _len;
      events = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), func = arguments[_i++];
      callback = (function(_this) {
        return function() {
          var event, _j, _len;
          for (_j = 0, _len = events.length; _j < _len; _j++) {
            event = events[_j];
            removeEventListener(_this.element, event, callback);
          }
          func.apply(_this, [_this.element]);
        };
      })(this);
      for (_j = 0, _len = events.length; _j < _len; _j++) {
        event = events[_j];
        addEventListener(this.element, event, callback);
      }
    };

    Element.prototype.addClass = function(className) {
      if (!hasClass(this.element, className)) {
        addClass(this.element, className);
      }
    };

    Element.prototype.removeClass = function(className) {
      if (hasClass(this.element, className)) {
        removeClass(this.element, className);
      }
    };

    Element.prototype.hasClass = function(className) {
      return hasClass(this.element, className);
    };

    addEventListener = function(element, event, func) {
      if (element.addEventListener) {
        element.addEventListener("" + event, func);
      } else {
        element.attachEvent("on" + event, func);
      }
    };

    removeEventListener = function(element, event, func) {
      if (element.removeEventListener) {
        element.removeEventListener("" + event, func);
      } else {
        element.detachEvent("on" + event, func);
      }
    };

    r_whitespace = /[ \t\n\f\r]+/g;

    r_leading_and_trailing_whitespace = /^[ \t\n\f\r]+|[ \t\n\f\r]+$/g;

    addClass = function(element, className) {
      element.className += " " + className;
    };

    removeClass = function(element, className) {
      element.className = (" " + element.className + " ").replace(r_whitespace, " ").replace(" " + className + " ", "").replace(r_leading_and_trailing_whitespace, "");
    };

    hasClass = function(element, className) {
      return (" " + element.className + " ").replace(r_whitespace, " ").indexOf(" " + className + " ") >= 0;
    };

    return Element;

  })();

  Frame = (function(_super) {
    __extends(Frame, _super);

    function Frame(callback) {
      Frame.__super__.constructor.call(this, "iframe", function(iframe) {
        var key, value, _ref, _ref1;
        _ref = {
          allowtransparency: true,
          scrolling: "no",
          frameBorder: 0
        };
        for (key in _ref) {
          value = _ref[key];
          iframe.setAttribute(key, value);
        }
        _ref1 = {
          border: "none",
          height: "0",
          width: "1px"
        };
        for (key in _ref1) {
          value = _ref1[key];
          iframe.style[key] = value;
        }
        if (callback) {
          callback.apply(this, [iframe]);
        }
      });
    }

    Frame.prototype.html = function(html) {
      var contentDocument;
      try {
        contentDocument = this.element.contentWindow.document;
        contentDocument.open();
        contentDocument.write(html);
        contentDocument.close();
      } catch (_error) {}
    };

    Frame.prototype.load = function(src) {
      return this.element.src = src;
    };

    Frame.prototype.size = function() {
      var body, contentDocument, html, size;
      try {
        contentDocument = this.element.contentWindow.document;
        html = contentDocument.documentElement;
        body = contentDocument.body;
        html.style.overflow = body.style.overflow = window.opera ? "scroll" : "visible";
        size = {
          width: "" + body.scrollWidth + "px",
          height: "" + body.scrollHeight + "px"
        };
        html.style.overflow = body.style.overflow = "";
        return size;
      } catch (_error) {
        return {};
      }
    };

    Frame.prototype.resize = function(_arg) {
      var height, width, _ref;
      _ref = _arg != null ? _arg : this.size(), width = _ref.width, height = _ref.height;
      if (width) {
        this.element.style.width = width;
      }
      if (height) {
        return this.element.style.height = height;
      }
    };

    return Frame;

  })(Element);

  ButtonAnchor = (function() {
    var filter_js;

    function ButtonAnchor() {}

    ButtonAnchor.parse = function(element) {
      return {
        href: filter_js(element.href),
        text: element.getAttribute("data-text") || element.textContent || element.innerText,
        data: {
          count: {
            api: (function() {
              var api;
              if (api = element.getAttribute("data-count-api")) {
                if ("/" !== api.charAt(0)) {
                  api = "/" + api;
                }
                return api;
              }
            })(),
            href: (function() {
              var href;
              if ((href = element.getAttribute("data-count-href")) && (href = filter_js(href))) {
                return href;
              } else {
                return filter_js(element.href);
              }
            })()
          },
          style: (function() {
            var i, style, _i, _len, _ref;
            if (style = element.getAttribute("data-style")) {
              _ref = Config.styles;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                i = _ref[_i];
                if (i === style) {
                  return style;
                }
              }
            }
            return Config.styles[0];
          })(),
          icon: (function() {
            var icon;
            if (icon = element.getAttribute("data-icon")) {
              return icon;
            }
          })()
        }
      };
    };

    filter_js = function(href) {
      if (!/^\s*javascript:/i.test(href)) {
        return href;
      }
    };

    return ButtonAnchor;

  })();

  ButtonFrame = (function(_super) {
    __extends(ButtonFrame, _super);

    function ButtonFrame() {
      var callback, hash, reload;
      hash = arguments[0], callback = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      ButtonFrame.__super__.constructor.call(this, callback[0]);
      reload = (function(_this) {
        return function() {
          var size;
          size = _this.size();
          _this.once("load", function(element) {
            this.resize(size);
            if (callback[1]) {
              callback[1](element);
            }
          });
          _this.load("" + Config.url + "buttons.html" + hash);
        };
      })(this);
      this.once("load", function(element) {
        var script;
        if (element.contentWindow.callback) {
          script = element.contentWindow.callback.script;
          if (script.readyState) {
            new Element(script).on("readystatechange", function() {
              if (/loaded|complete/.test(script.readyState)) {
                reload();
              }
            });
          } else {
            new Element(script).on("load", "error", function() {
              reload();
            });
          }
        } else {
          reload();
        }
      });
      this.html("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<title></title>\n<base target=\"_blank\"><!--[if lte IE 6]></base><![endif]-->\n<link rel=\"stylesheet\" href=\"" + Config.url + "assets/css/buttons.css\">\n<style>html{visibility:hidden;}</style>\n<script>document.location.hash = \"" + hash + "\";</script>\n</head>\n<body>\n<script src=\"" + Config.script.src + "\"></script>\n</body>\n</html>");
    }

    return ButtonFrame;

  })(Frame);

  ButtonFrameContent = (function() {
    var Button, Count;

    function ButtonFrameContent(options) {
      if (options && options.data) {
        document.body.className = options.data.style;
        document.getElementsByTagName("base")[0].href = options.href;
        new Button(options, function(buttonElement) {
          document.body.appendChild(buttonElement);
        });
        new Count(options, function(countElement) {
          document.body.appendChild(countElement);
        });
      }
    }

    Button = (function(_super) {
      __extends(Button, _super);

      function Button(options, callback) {
        Button.__super__.constructor.call(this, "a", function(a) {
          a.className = "button";
          if (options.href) {
            a.href = options.href;
          }
          new Element("i", function(icon) {
            icon = document.createElement("i");
            icon.className = (function() {
              var classNames;
              classNames = [options.data.icon || Config.icon];
              if (Config.iconClass) {
                classNames.push(Config.iconClass);
              }
              return classNames.join(" ");
            })();
            a.appendChild(icon);
          });
          new Element("span", function(text) {
            text.appendChild(document.createTextNode(" "));
            a.appendChild(text);
          });
          new Element("span", function(text) {
            if (options.text) {
              text.appendChild(document.createTextNode(options.text));
            }
            a.appendChild(text);
          });
          if (callback) {
            callback(a);
          }
        });
      }

      return Button;

    })(Element);

    Count = (function(_super) {
      __extends(Count, _super);

      function Count(options, callback) {
        if (options.data.count.api) {
          Count.__super__.constructor.call(this, "a", function(a) {
            a.className = "count";
            if (options.data.count.href) {
              a.href = options.data.count.href;
            }
            new Element("b", function(b) {
              a.appendChild(b);
            });
            new Element("i", function(i) {
              a.appendChild(i);
            });
            new Element("span", function(text) {
              var endpoint;
              a.appendChild(text);
              endpoint = (function() {
                var query, url;
                url = options.data.count.api.split("#")[0];
                query = QueryString.parse(url.split("?").slice(1).join("?"));
                query.callback = "callback";
                return "" + (url.split("?")[0]) + "?" + (QueryString.stringify(query));
              })();
              new Element("script", function(script) {
                var head;
                script.async = true;
                script.src = "" + Config.api + endpoint;
                window.callback = function(json) {
                  var data;
                  window.callback = null;
                  if (json.meta.status === 200) {
                    data = FlatObject.flatten(json.data)[options.data.count.api.split("#").slice(1).join("#")];
                    if (Object.prototype.toString.call(data) === "[object Number]") {
                      data = data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                    }
                    text.appendChild(document.createTextNode(" " + data + " "));
                    if (callback) {
                      callback(a);
                    }
                  }
                };
                window.callback.script = script;
                this.on("error", function() {
                  window.callback = null;
                });
                if (script.readyState) {
                  this.on("readystatechange", function() {
                    if (script.readyState === "loaded" && script.children && script.readyState === "loading") {
                      window.callback = null;
                    }
                  });
                }
                head = document.getElementsByTagName("head")[0];
                head.insertBefore(script, head.firstChild);
              });
            });
          });
        }
      }

      return Count;

    })(Element);

    return ButtonFrameContent;

  })();

  if (Config.script) {
    if (document.querySelectorAll) {
      anchors = document.querySelectorAll("a." + Config.anchorClass);
    } else {
      anchors = (function() {
        var _i, _len, _ref, _results;
        _ref = document.getElementsByTagName("a");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          anchor = _ref[_i];
          if (Element.prototype.hasClass.call({
            element: anchor
          }, Config.anchorClass)) {
            _results.push(anchor);
          }
        }
        return _results;
      })();
    }
    _fn = function(a) {
      new ButtonFrame(Hash.encode(ButtonAnchor.parse(a)), function(iframe) {
        a.parentNode.insertBefore(iframe, a);
      }, function() {
        a.parentNode.removeChild(a);
      });
    };
    for (_i = 0, _len = anchors.length; _i < _len; _i++) {
      anchor = anchors[_i];
      _fn(anchor);
    }
  } else {
    new ButtonFrameContent(Hash.decode());
  }

}).call(this);
