// Generated by CoffeeScript 1.9.0
(function() {
  var ButtonAnchor, ButtonForm, ButtonFrame, ButtonFrameContent, Code, Config, DisabledFrame, Element, FlatObject, Form, Frame, GitHubAPIStatus, Hash, PreviewAnchor, PreviewFrame, QueryString, iframe, _i, _len, _ref,
    __slice = [].slice,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  Config = {
    api: "https://api.github.com",
    anchorClass: "github-button",
    iconClass: "octicon",
    icon: "octicon-mark-github",
    scriptId: "github-bjs",
    styles: ["default", "mega"]
  };

  if (Config.script = document.getElementById(Config.scriptId)) {
    Config.url = Config.script.src.replace(/[?#].*$/, "").replace(/buttons.js$/, "");
  }

  FlatObject = (function() {
    var __toString;

    function FlatObject() {}

    FlatObject.flatten = function(obj) {
      var flatten, result;
      flatten = function(object, super_key) {
        var index, item, key, value, _i, _len;
        switch (__toString.call(object)) {
          case "[object Object]":
            for (key in object) {
              value = object[key];
              flatten(value, super_key ? super_key + "." + key : key);
            }
            break;
          case "[object Array]":
            for (index = _i = 0, _len = object.length; _i < _len; index = ++_i) {
              item = object[index];
              flatten(item, super_key ? super_key + "[" + index + "]" : "[" + index + "]");
            }
            break;
          default:
            result[super_key] = object;
        }
      };
      result = {};
      flatten(obj);
      return result;
    };

    FlatObject.expand = function(obj) {
      var flat_key, key, keys, match, namespace, sub_key, target, value, _i, _j, _len, _len1, _ref, _ref1;
      namespace = [];
      for (flat_key in obj) {
        value = obj[flat_key];
        keys = [];
        _ref = flat_key.split(".");
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          match = key.match(/^(.*?)((?:\[[0-9]+\])*)$/);
          if (match[1]) {
            keys.push(match[1]);
          }
          if (match[2]) {
            _ref1 = match[2].replace(/^\[|\]$/g, "").split("][");
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              sub_key = _ref1[_j];
              keys.push(Number(sub_key));
            }
          }
        }
        target = namespace;
        key = 0;
        while (keys.length) {
          if (target[key] == null) {
            switch (__toString.call(keys[0])) {
              case "[object String]":
                target[key] = {};
                break;
              case "[object Number]":
                target[key] = [];
            }
          }
          target = target[key];
          key = keys.shift();
        }
        target[key] = value;
      }
      return namespace[0];
    };

    __toString = Object.prototype.toString;

    return FlatObject;

  })();

  QueryString = (function() {
    function QueryString() {}

    QueryString.stringify = function(obj) {
      var key, results, value;
      results = [];
      for (key in obj) {
        value = obj[key];
        if (value == null) {
          value = "";
        }
        results.push(key + "=" + value);
      }
      return results.join("&");
    };

    QueryString.parse = function(str) {
      var key, obj, pair, value, _i, _len, _ref, _ref1;
      obj = {};
      _ref = str.split("&");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pair = _ref[_i];
        if (!(pair !== "")) {
          continue;
        }
        _ref1 = pair.split("="), key = _ref1[0], value = 2 <= _ref1.length ? __slice.call(_ref1, 1) : [];
        if (key !== "") {
          obj[key] = value.join("=");
        }
      }
      return obj;
    };

    return QueryString;

  })();

  Hash = (function() {
    function Hash() {}

    Hash.encode = function(data) {
      return "#" + encodeURIComponent(QueryString.stringify(FlatObject.flatten(data)));
    };

    Hash.decode = function(data) {
      if (data == null) {
        data = document.location.hash;
      }
      return (FlatObject.expand(QueryString.parse(decodeURIComponent(data.replace(/^#/, ""))))) || {};
    };

    return Hash;

  })();

  Element = (function() {
    var addClass, addEventListener, hasClass, r_leading_and_trailing_whitespace, r_whitespace, removeClass, removeEventListener;

    function Element(element, callback) {
      this.$ = element && element.nodeType === 1 ? element : document.createElement(element);
      if (callback) {
        callback.apply(this, [this.$]);
      }
    }

    Element.prototype.get = function() {
      return this.$;
    };

    Element.prototype.on = function() {
      var callback, eventName, events, func, _i, _j, _len;
      events = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), func = arguments[_i++];
      callback = (function(_this) {
        return function(event) {
          return func.apply(_this, [event || window.event]);
        };
      })(this);
      for (_j = 0, _len = events.length; _j < _len; _j++) {
        eventName = events[_j];
        addEventListener(this.$, eventName, callback);
      }
    };

    Element.prototype.once = function() {
      var callback, eventName, events, func, _i, _j, _len;
      events = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), func = arguments[_i++];
      callback = (function(_this) {
        return function(event) {
          var eventName, _j, _len;
          for (_j = 0, _len = events.length; _j < _len; _j++) {
            eventName = events[_j];
            removeEventListener(_this.$, eventName, callback);
          }
          return func.apply(_this, [event || window.event]);
        };
      })(this);
      for (_j = 0, _len = events.length; _j < _len; _j++) {
        eventName = events[_j];
        addEventListener(this.$, eventName, callback);
      }
    };

    Element.prototype.addClass = function(className) {
      if (!hasClass(this.$, className)) {
        addClass(this.$, className);
      }
    };

    Element.prototype.removeClass = function(className) {
      if (hasClass(this.$, className)) {
        removeClass(this.$, className);
      }
    };

    Element.prototype.hasClass = function(className) {
      return hasClass(this.$, className);
    };

    addEventListener = function(element, event, func) {
      if (element.addEventListener) {
        element.addEventListener("" + event, func);
      } else {
        element.attachEvent("on" + event, func);
      }
    };

    removeEventListener = function(element, event, func) {
      if (element.removeEventListener) {
        element.removeEventListener("" + event, func);
      } else {
        element.detachEvent("on" + event, func);
      }
    };

    r_whitespace = /[ \t\n\f\r]+/g;

    r_leading_and_trailing_whitespace = /^[ \t\n\f\r]+|[ \t\n\f\r]+$/g;

    addClass = function(element, className) {
      element.className += " " + className;
    };

    removeClass = function(element, className) {
      element.className = (" " + element.className + " ").replace(r_whitespace, " ").replace(" " + className + " ", "").replace(r_leading_and_trailing_whitespace, "");
    };

    hasClass = function(element, className) {
      return (" " + element.className + " ").replace(r_whitespace, " ").indexOf(" " + className + " ") >= 0;
    };

    return Element;

  })();

  Frame = (function(_super) {
    __extends(Frame, _super);

    function Frame(callback) {
      Frame.__super__.constructor.call(this, "iframe", function(iframe) {
        var key, value, _ref, _ref1;
        _ref = {
          allowtransparency: true,
          scrolling: "no",
          frameBorder: 0
        };
        for (key in _ref) {
          value = _ref[key];
          iframe.setAttribute(key, value);
        }
        _ref1 = {
          border: "none",
          height: "0",
          width: "1px"
        };
        for (key in _ref1) {
          value = _ref1[key];
          iframe.style[key] = value;
        }
        if (callback) {
          callback.apply(this, [iframe]);
        }
      });
    }

    Frame.prototype.html = function(html) {
      var contentDocument;
      try {
        contentDocument = this.$.contentWindow.document;
        contentDocument.open();
        contentDocument.write(html);
        contentDocument.close();
      } catch (_error) {}
    };

    Frame.prototype.load = function(src) {
      return this.$.src = src;
    };

    Frame.prototype.size = function() {
      var body, contentDocument, html, size;
      try {
        contentDocument = this.$.contentWindow.document;
        html = contentDocument.documentElement;
        body = contentDocument.body;
        html.style.overflow = body.style.overflow = window.opera ? "scroll" : "visible";
        size = {
          width: body.scrollWidth + "px",
          height: body.scrollHeight + "px"
        };
        html.style.overflow = body.style.overflow = "";
        return size;
      } catch (_error) {
        return {};
      }
    };

    Frame.prototype.resize = function(_arg) {
      var height, width, _ref;
      _ref = _arg != null ? _arg : this.size(), width = _ref.width, height = _ref.height;
      if (width) {
        this.$.style.width = width;
      }
      if (height) {
        return this.$.style.height = height;
      }
    };

    return Frame;

  })(Element);

  ButtonAnchor = (function() {
    var filter_js;

    function ButtonAnchor() {}

    ButtonAnchor.parse = function(element) {
      var href, icon, style;
      return {
        href: filter_js(element.href),
        text: element.getAttribute("data-text") || element.textContent || element.innerText,
        data: {
          count: {
            api: (function() {
              var api;
              if (api = element.getAttribute("data-count-api")) {
                if ("/" !== api.charAt(0)) {
                  api = "/" + api;
                }
                return api;
              }
            })(),
            href: (href = element.getAttribute("data-count-href")) && (href = filter_js(href)) ? href : filter_js(element.href)
          },
          style: (style = element.getAttribute("data-style")) ? style : void 0,
          icon: (icon = element.getAttribute("data-icon")) ? icon : void 0
        }
      };
    };

    filter_js = function(href) {
      if (!/^\s*javascript:/i.test(href)) {
        return href;
      }
    };

    return ButtonAnchor;

  })();

  ButtonFrame = (function(_super) {
    __extends(ButtonFrame, _super);

    function ButtonFrame() {
      var callbacks, hash, reload;
      hash = arguments[0], callbacks = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      ButtonFrame.__super__.constructor.call(this, callbacks.shift());
      reload = (function(_this) {
        return function() {
          var size;
          size = _this.size();
          _this.once("load", function() {
            this.resize(size);
            if (callbacks[0]) {
              callbacks.shift()(this.$);
            }
          });
          _this.load(Config.url + "buttons.html" + hash);
        };
      })(this);
      this.once("load", function() {
        var callback, script;
        if (callback = this.$.contentWindow.callback) {
          script = callback.script;
          if (script.readyState) {
            new Element(script).on("readystatechange", function() {
              if (/loaded|complete/.test(script.readyState)) {
                reload();
              }
            });
          } else {
            new Element(script).on("load", "error", function() {
              reload();
            });
          }
        } else {
          reload();
        }
      });
      this.html("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<title></title>\n<base target=\"_blank\"><!--[if lte IE 6]></base><![endif]-->\n<link rel=\"stylesheet\" href=\"" + Config.url + "assets/css/buttons.css\">\n<style>html{visibility:hidden;}</style>\n<script>document.location.hash = \"" + hash + "\";</script>\n</head>\n<body>\n<script src=\"" + Config.script.src + "\"></script>\n</body>\n</html>");
    }

    return ButtonFrame;

  })(Frame);

  ButtonFrameContent = (function() {
    var Button, Count;

    function ButtonFrameContent(options) {
      if (options && options.data) {
        document.body.className = (function() {
          var i, _i, _len, _ref;
          _ref = Config.styles;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            i = _ref[_i];
            if (i === options.data.style) {
              return i;
            }
          }
          return Config.styles[0];
        })();
        document.getElementsByTagName("base")[0].href = options.href;
        new Button(options, function(buttonElement) {
          document.body.appendChild(buttonElement);
        });
        new Count(options, function(countElement) {
          document.body.appendChild(countElement);
        });
      }
    }

    Button = (function(_super) {
      __extends(Button, _super);

      function Button(options, callback) {
        Button.__super__.constructor.call(this, "a", function(a) {
          a.className = "button";
          if (options.href) {
            a.href = options.href;
          }
          new Element("i", function(icon) {
            icon = document.createElement("i");
            icon.className = (function() {
              var classNames;
              classNames = [options.data.icon || Config.icon];
              if (Config.iconClass) {
                classNames.push(Config.iconClass);
              }
              return classNames.join(" ");
            })();
            a.appendChild(icon);
          });
          new Element("span", function(text) {
            text.appendChild(document.createTextNode(" "));
            a.appendChild(text);
          });
          new Element("span", function(text) {
            if (options.text) {
              text.appendChild(document.createTextNode(options.text));
            }
            a.appendChild(text);
          });
          if (callback) {
            callback(a);
          }
        });
      }

      return Button;

    })(Element);

    Count = (function(_super) {
      __extends(Count, _super);

      function Count(options, callback) {
        if (options.data.count.api) {
          Count.__super__.constructor.call(this, "a", function(a) {
            a.className = "count";
            if (options.data.count.href) {
              a.href = options.data.count.href;
            }
            new Element("b", function(b) {
              a.appendChild(b);
            });
            new Element("i", function(i) {
              a.appendChild(i);
            });
            new Element("span", function(text) {
              var endpoint;
              a.appendChild(text);
              endpoint = (function() {
                var query, url;
                url = options.data.count.api.split("#")[0];
                query = QueryString.parse(url.split("?").slice(1).join("?"));
                query.callback = "callback";
                return (url.split("?")[0]) + "?" + (QueryString.stringify(query));
              })();
              new Element("script", function(script) {
                var head;
                script.async = true;
                script.src = "" + Config.api + endpoint;
                window.callback = function(json) {
                  var data;
                  window.callback = null;
                  if (json.meta.status === 200) {
                    data = FlatObject.flatten(json.data)[options.data.count.api.split("#").slice(1).join("#")];
                    if (Object.prototype.toString.call(data) === "[object Number]") {
                      data = data.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                    }
                    text.appendChild(document.createTextNode(" " + data + " "));
                    if (callback) {
                      callback(a);
                    }
                  }
                };
                window.callback.script = script;
                this.on("error", function() {
                  window.callback = null;
                });
                if (script.readyState) {
                  this.on("readystatechange", function() {
                    if (script.readyState === "loaded" && script.children && script.readyState === "loading") {
                      window.callback = null;
                    }
                  });
                }
                head = document.getElementsByTagName("head")[0];
                head.insertBefore(script, head.firstChild);
              });
            });
          });
        }
      }

      return Count;

    })(Element);

    return ButtonFrameContent;

  })();

  GitHubAPIStatus = (function() {
    function GitHubAPIStatus() {}

    GitHubAPIStatus.low_rate_limit = false;

    window.callback = function(json) {
      GitHubAPIStatus.rate_limit = json.data;
      GitHubAPIStatus.low_rate_limit = GitHubAPIStatus.rate_limit.resources.core.remaining < 16;
    };

    GitHubAPIStatus.update = function() {
      if (!window.callback.script) {
        new Element("script", function(script) {
          var head;
          script.async = true;
          script.src = "https://api.github.com/rate_limit?callback=callback";
          window.callback.script = script;
          this.on("readystatechange", "load", "error", function() {
            if (!script.readyState || /loaded|complete/.test(script.readyState)) {
              script.parentNode.removeChild(script);
              window.callback.script = null;
            }
          });
          head = document.getElementsByTagName("head")[0];
          head.insertBefore(script, head.firstChild);
        });
      }
    };

    GitHubAPIStatus.update();

    return GitHubAPIStatus;

  })();

  Form = (function(_super) {
    __extends(Form, _super);

    function Form() {
      return Form.__super__.constructor.apply(this, arguments);
    }

    Form.prototype.on = function() {
      var callback, element, events, func, _i, _j, _len, _ref;
      events = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), func = arguments[_i++];
      if (events.indexOf("change") >= 0) {
        callback = (function(_this) {
          return function(event) {
            return func.apply(_this, [event || window.event]);
          };
        })(this);
        _ref = this.get().elements;
        for (_j = 0, _len = _ref.length; _j < _len; _j++) {
          element = _ref[_j];
          new Element(element).on("change", "input", callback);
        }
      }
      return Form.__super__.on.apply(this, arguments);
    };

    Form.prototype.serialize = function() {
      var data, node, _i, _len, _ref;
      data = {};
      _ref = this.get().elements;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        node = _ref[_i];
        if (node.name) {
          switch (node.type) {
            case "radio":
            case "checkbox":
              if (node.checked) {
                data[node.name] = node.value;
              }
              break;
            default:
              data[node.name] = node.value;
          }
        }
      }
      return data;
    };

    return Form;

  })(Element);

  DisabledFrame = (function(_super) {
    __extends(DisabledFrame, _super);

    function DisabledFrame() {
      DisabledFrame.__super__.constructor.apply(this, arguments);
      this.on("load", function() {
        var a, _i, _len, _ref;
        _ref = this.get().contentWindow.document.getElementsByTagName("a");
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          a = _ref[_i];
          new Element(a).on("click", function(event) {
            event.preventDefault();
            return false;
          });
        }
        new Element(this.get().contentWindow.document.body).on("click", (function(_this) {
          return function() {
            _this.get().parentNode.click();
          };
        })(this));
      });
    }

    return DisabledFrame;

  })(Element);

  PreviewAnchor = (function(_super) {
    __extends(PreviewAnchor, _super);

    function PreviewAnchor(_arg, callback) {
      var data, href, text;
      href = _arg.href, text = _arg.text, data = _arg.data;
      PreviewAnchor.__super__.constructor.call(this, "a", function(a) {
        var name, value;
        a.className = Config.anchorClass;
        a.href = href;
        a.appendChild(document.createTextNode("" + text));
        for (name in data) {
          value = data[name];
          a.setAttribute("data-" + name, value);
        }
        if (callback) {
          callback(a);
        }
      });
    }

    return PreviewAnchor;

  })(Element);

  PreviewFrame = (function(_super) {
    __extends(PreviewFrame, _super);

    function PreviewFrame(_at_$) {
      this.$ = _at_$;
      this.on("load", function() {
        var callback, script;
        if (callback = this.get().contentWindow.callback) {
          script = callback.script;
          if (script.readyState) {
            new Element(script).on("readystatechange", function() {
              if (/loaded|complete/.test(script.readyState)) {
                this.resize();
              }
            });
          } else {
            new Element(script).on("load", "error", function() {
              this.resize();
            });
          }
        } else {
          this.resize();
        }
      });
    }

    PreviewFrame.prototype.load = function(config) {
      this.get().parentNode.style.height = ((config.data.style === "mega" ? 28 : 20) + 2) + "px";
      this.get().style.width = "1px";
      this.get().style.height = "0";
      this.get().src = "buttons.html" + (Hash.encode(config));
      this.get().contentWindow.document.location.reload();
    };

    return PreviewFrame;

  })(Frame);

  Code = (function(_super) {
    __extends(Code, _super);

    function Code() {
      Code.__super__.constructor.apply(this, arguments);
      this.on("focus", function() {
        this.get().select();
      });
      this.on("click", function() {
        this.get().select();
      });
      this.on("mouseup", function(event) {
        event.preventDefault();
        return false;
      });
    }

    return Code;

  })(Element);

  ButtonForm = (function(_super) {
    __extends(ButtonForm, _super);

    function ButtonForm(_at_$, _arg) {
      var button, callback, code, content, frame, snippet, user_repo, warning, _ref;
      this.$ = _at_$;
      content = _arg.content, (_ref = _arg.preview, button = _ref.button, frame = _ref.frame, code = _ref.code, warning = _ref.warning), snippet = _arg.snippet, user_repo = _arg.user_repo;
      snippet.get().value = "<!-- Place this tag right after the last button or just before your close body tag. -->\n<script async defer id=\"github-bjs\" src=\"https://buttons.github.io/buttons.js\"></script>";
      callback = (function(_this) {
        return function(_arg1) {
          var cache, force, name, options, _i, _j, _len, _len1, _ref1, _ref2;
          force = _arg1.force;
          options = _this.serialize();
          if (options.type) {
            content.removeClass("hidden");
            _ref1 = ["repo", "standard-icon"];
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              name = _ref1[_i];
              _this.get().elements[name].disabled = options.type === "follow";
            }
            _ref2 = ["show-count"];
            for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
              name = _ref2[_j];
              _this.get().elements[name].disabled = options.type === "download";
            }
            if (!((!options.user || /^[a-z0-9][a-z0-9-]*$/i.test(options.user)) && (options.type === "follow" || !options.repo || (/^[\w.-]+$/.test(options.repo) && !/^\.\.?$/.test(options.repo))))) {
              user_repo.addClass("has-error");
            } else {
              user_repo.removeClass("has-error");
              if (options.user === "" || (options.type !== "follow" && options.repo === "")) {
                user_repo.addClass("has-warning");
              } else {
                user_repo.removeClass("has-warning");
              }
            }
            if ((user_repo.hasClass("has-error")) || (user_repo.hasClass("has-warning"))) {
              options.user = "ntkme";
              options.repo = "github-buttons";
            }
            if (_this.cache !== (cache = Hash.encode(options)) || force) {
              _this.cache = cache;
              new PreviewAnchor(_this.parse(options), function(a) {
                var reset;
                code.get().value = "<!-- Place this tag where you want the button to render. -->\n" + a.outerHTML;
                button.addClass("hidden");
                if ((options["show-count"] != null) && options.type !== "download") {
                  GitHubAPIStatus.update();
                  if (GitHubAPIStatus.low_rate_limit) {
                    button.removeClass("hidden");
                    reset = new Date(GitHubAPIStatus.rate_limit.resources.core.reset * 1000);
                    if (!_this.reset || reset > _this.reset) {
                      _this.reset = reset;
                      warning.removeClass("hidden");
                    }
                    if (force) {
                      warning.addClass("hidden");
                    } else {
                      a.removeAttribute("data-count-api");
                    }
                  }
                }
                frame.load(ButtonAnchor.parse(a));
                a = null;
              });
            }
          }
        };
      })(this);
      button.on("click", function(event) {
        event.preventDefault();
        callback({
          force: true
        });
        return false;
      });
      this.on("change", callback);
    }

    ButtonForm.prototype.parse = function(options) {
      var config, repo, type, user;
      if (options == null) {
        options = this.serialize();
      }
      type = options.type, user = options.user, repo = options.repo;
      config = {
        className: "github-button",
        href: (function() {
          switch (type) {
            case "follow":
              return "https://github.com/" + user;
            case "watch":
            case "star":
            case "fork":
              return "https://github.com/" + user + "/" + repo;
            case "issue":
              return "https://github.com/" + user + "/" + repo + "/issues";
            case "download":
              return "https://github.com/" + user + "/" + repo + "/archive/master.zip";
            default:
              return "https://github.com/";
          }
        })(),
        text: (function() {
          switch (type) {
            case "follow":
              return "Follow @" + user;
            default:
              return type.charAt(0).toUpperCase() + type.slice(1).toLowerCase();
          }
        })(),
        data: {
          icon: (function() {
            switch (type) {
              case "watch":
                return "octicon-eye";
              case "star":
                return "octicon-star";
              case "fork":
                return "octicon-git-branch";
              case "issue":
                return "octicon-issue-opened";
              case "download":
                return "octicon-cloud-download";
              default:
                return "octicon-mark-github";
            }
          })()
        }
      };
      if (options["large-button"] != null) {
        config.data.style = "mega";
      }
      if (options["show-count"] != null) {
        switch (type) {
          case "follow":
            config.data["count-href"] = "/" + user + "/followers";
            config.data["count-api"] = "/users/" + user + "#followers";
            break;
          case "watch":
            config.data["count-href"] = "/" + user + "/" + repo + "/watchers";
            config.data["count-api"] = "/repos/" + user + "/" + repo + "#subscribers_count";
            break;
          case "star":
            config.data["count-href"] = "/" + user + "/" + repo + "/stargazers";
            config.data["count-api"] = "/repos/" + user + "/" + repo + "#stargazers_count";
            break;
          case "fork":
            config.data["count-href"] = "/" + user + "/" + repo + "/network";
            config.data["count-api"] = "/repos/" + user + "/" + repo + "#forks_count";
            break;
          case "issue":
            config.data["count-api"] = "/repos/" + user + "/" + repo + "#open_issues_count";
        }
      }
      if ((options["standard-icon"] != null) || config.data.icon === "octicon-mark-github") {
        delete config.data.icon;
      }
      return config;
    };

    return ButtonForm;

  })(Form);

  _ref = document.getElementsByTagName("iframe");
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    iframe = _ref[_i];
    if (iframe.parentNode.id !== "preview") {
      new DisabledFrame(iframe);
    }
  }

  new ButtonForm(document.getElementById("button-config"), {
    content: new Element(document.getElementById("content")),
    user_repo: new Element(document.getElementById("user-repo")),
    preview: {
      button: new Element(document.getElementById("preview-button")),
      frame: new PreviewFrame(document.getElementById("preview").getElementsByTagName("iframe")[0]),
      code: new Code(document.getElementById("code")),
      warning: new Element(document.getElementById("preview-warning"))
    },
    snippet: new Code(document.getElementById("snippet"))
  });

  this.onbeforeunload = function() {};

}).call(this);
