// Generated by CoffeeScript 1.10.0
(function() {
  var args, fs, page, puts;

  args = require('system').args;

  fs = require('fs');

  page = require('webpage').create();

  if (args.length > 1) {
    puts = function(content) {
      return fs.write(args[1], content, 'w');
    };
  } else {
    puts = function(content) {
      return console.log(content);
    };
  }

  page.open("src/phantomjs/octicons/index.html", function() {
    puts(page.evaluate(function() {
      var styleSheets;
      styleSheets = Array.prototype.filter.call(document.styleSheets, function(styleSheet) {
        var ref;
        return (ref = styleSheet.href) != null ? ref.match(/\/octicons\.css$/) : void 0;
      });
      return Array.prototype.filter.call(styleSheets[0].cssRules, function(cssRule) {
        var ref;
        return (ref = cssRule.selectorText) != null ? ref.match(/^\.octicon-[\w-]+?::before(?:\s*,\s*\.octicon-[\w-]+?::before)*$/) : void 0;
      }).map(function(cssRule) {
        var char, charCode, selectorText;
        selectorText = cssRule.selectorText.replace(/::before/g, "");
        char = cssRule.style.content;
        charCode = char.charCodeAt(0).toString(16);
        return selectorText + " { zoom: expression( this.innerHTML = '&#x" + charCode + ";' ); } /* " + char + " */";
      }).join("\n");
    }));
    return phantom.exit();
  });

}).call(this);
