name: build

on: [push, pull_request]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        browser:
          - ChromeHeadless
          - FirefoxHeadless

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test -- --browsers ${{ matrix.browser }}

      - name: Diff
        run: git diff --exit-code

  dependabot:

    if: github.event.repository.fork == false && github.event.pull_request.user.login == 'dependabot[bot]'

    needs: [build]

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v3

      - name: Enable auto-merge for Dependabot PRs
        if: steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ github.token }}
